function test_mob(p: player):
  send "§5Testing mob_main" to the console
  set {_location} to location of {_p}
  it "Test mob summon":
    set {_zombie} to mob_summon("ZOMBIE", "1", {_location})
    loop {STAT::MOB::*}:
      set {_stat} to loop-value
      set {_value} to {MOB::ZOMBIE::1::%{_stat}%}
      set {_current} to entity_get_stat({_zombie}, {_stat})
      if {_value} is set:
        assert if {_value} is {_current} with message "Mob %{_stat}% should be %{_value}%. Got %{_current}%"
    set {_type} to entity_get_tag({_zombie}, "TYPE")
    set {_category} to entity_get_tag({_zombie}, "CATEGORY")
    set {_id} to entity_get_tag({_zombie}, "ID")
    assert if {_type} is "MOB" with message "mob type should be MOB. Got %{_type}%"
    assert if {_category} is "ZOMBIE" with message "mob category should be ZOMBIE. Got %{_category}%"
    assert if {_id} is "1" with message "mob id should be 1. Got %{_id}%"
    kill {_zombie}