# -TYPE- ; ALL, TRYNDAMERE, FALL, BURN, LAVA
# -BEHAVIOR- : DURATION, UNIQUE
function entity_effect_immunity(entity: entity, type: text, duration: number, behavior: text = "DURATION"):
  replace "IMMUNITY_" with "" in {_type}
  entity_store_effect_init({_entity}, "IMMUNITY_%{_type}%", {_duration})
  entity_store_effect_set({_entity}, "IMMUNITY_%{_type}%", "BEHAVIOR", {_behavior})
  while entity_store_effect_isset({_entity}, "IMMUNITY_%{_type}%") is true:
    entity_store_effect_add({_entity}, "IMMUNITY_%{_type}%", "duration", -5)
    wait 5 ticks
