DURATION: 1200
MOBS:
  1:
    ID: ZOMBIE
    LEVEL: 1
    AMOUNT: 30
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 20
  2:
    ID: SKELETON
    LEVEL: 1
    AMOUNT: 30
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 20