DURATION: 1200
MOBS:
  1:
    ID: ZOMBIE
    LEVEL: 1
    AMOUNT: 30
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 50
  2:
    ID: VOID_WARRIOR
    LEVEL: 1
    AMOUNT: 30
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 50
  3:
    ID: VOID_ARCHER
    LEVEL: 0
    AMOUNT: 30
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 50