DURATION: 1200
MOBS:
  1:
    ID: ZOMBIE
    LEVEL: 1
    AMOUNT: 5
    AI: A
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 10
  2:
    ID: ZOMBIE
    LEVEL: 1
    AMOUNT: 5
    AI: A
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 10
  3:
    ID: SKELETON
    LEVEL: 0
    AMOUNT: 5
    AI: A
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 10