DURATION: 1200
MUSICS:
  - WAVE_2
  - WAVE_3
MOBS:
  1:
    ID: ZOMBIE
    LEVEL: 1
    AMOUNT: 40
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  2:
    ID: SPIDER
    LEVEL: 0
    AMOUNT: 20
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  3:
    ID: SKELETON
    LEVEL: 0
    AMOUNT: 30
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10