DURATION: 1200
MOBS:
  1:
    ID: VOID_WARRIOR
    LEVEL: 2
    AMOUNT: 20
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  2:
    ID: VOID_ARCHER
    LEVEL: 2
    AMOUNT: 30
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  3:
    ID: CREEPER
    LEVEL: 1
    AMOUNT: 30
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10