DURATION: 1200
MOBS:
  1:
    ID: ZOMBIE
    LEVEL: 3
    AMOUNT: 5
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  2:
    ID: SKELETON
    LEVEL: 3
    AMOUNT: 5
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10
  3:
    ID: CREEPER
    LEVEL: 3
    AMOUNT: 10
    AI: A
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10