DURATION: 4000
TYPE: BOSS
MUSICS:
  - BOSS_GOULIATH
MOBS:
  1:
    ID: BOSS_GOULIATH
    LEVEL: 1
    AMOUNT: 1
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 0
  2:
    ID: NORMAL_SPARTAN
    LEVEL: 1
    AMOUNT: 30
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 0