DURATION: 4000
TYPE: BOSS
MUSIC: GOULIATH
MOBS:
  1:
    ID: BOSS_GOULIATH
    LEVEL: 1
    AMOUNT: 1
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 0
  2:
    ID: NORMAL_SPARTAN
    LEVEL: 1
    AMOUNT: 30
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
    DELAY: 0
  3:
    ID: VOID_WARRIOR-FLY
    LEVEL: 1
    AMOUNT: 15
    AI: goToLisa0
    LOCATION:
      - CASTLE.GATE_A
      - CASTLE.GATE_B
      - CASTLE.GATE_C
      - CASTLE.GATE_D
    DELAY: 10