function player_store_status_set(p: player, key: text, value: object):
  set {players::%{_p}%::status::%{_key}%} to {_value}

function player_store_status_get(p: player, key: text) :: object:
  return {players::%{_p}%::status::%{_key}%}

function player_store_status_isset(p: player, key: text) :: boolean:
  if player_store_status_get({_p}, {_key}) is set:
    return true
  return false

function player_store_status_delete(p: player, key: text):
  delete {players::%{_p}%::status::%{_key}%}