ADMIN:
  COMMANDS:
    SUCCESS: "Commande exécutée avec succès !"
MESSAGE:
  PLAYER:
    MANA:
      NOT_ENOUGH: "Pas assez de mana"
    CD:
      SKILL:
        IN_PROGRESS: "Ce sort est en cooldown"
WAVE:
  TITLE: "Vague"
STAT:
  ATTACK:
    NORMAL: "Attaque"
  POWER:
    NORMAL: "Puissance"
  DEFENCE:
    NORMAL: "Défense"
  MR:
    NORMAL: "Res.Magique"
  HEALTH:
    NORMAL: "PV"
  HEALTH_MAX:
    NORMAL: "PV.Max"
  HEALTH_REGEN:
    NORMAL: "PV.Regen"
  MANA:
    NORMAL: "Mana"
  MANA_MAX:
    NORMAL: "Mana.Max"
  MANA_REGEN:
    NORMAL: "Mana.Regen"
WEAPON:
  STAFF:
    TEST:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE} infligeant {_POWER}."
    LIMB_OF_WISDOM:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule de portée {_RANGE} et infligeant {_ATTACK}"
  CROSSBOW:
    ARMADILLO:
      TITLE: "Armadillo"
      LORE: "Projette un carreau qui inflige {_ATTACK}."
EQUIPMENT:
  HELMET:
    LAUREL_CROWN:
      TITLE: "La couronne de laurier {_TIER}"
  CHESTPLATE:
    CHAINMAIL:
      TITLE: "Le plastron de cuir {_TIER}"
  LEGGING:
    LEATHER_JOGGING:
      TITLE: "Le jogging de cuir {_TIER}"
SKILL:
  HELMET:
    TEST:
      TITLE: "Le souffle du dragon"
      LORE: "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant {_ATTACK} dans un rayon de {_RADIUS}"
    BURNING_HEART:
      TITLE: "Tête brûlée"
      LORE: "Vous Foncez vers l'ennemi le plus proche dans votre direction, lui infligeant {_ATTACK} et repoussant les ennemis proches. Les ennemis repoussés sont brûlés et subissent {_EFFECT_ATTACK} toutes les {_EFFECT_FREQUENCY} pendant {_EFFECT_DURATION}. Portée maximale : {_RANGE}"
  CHESTPLATE:
    BURNING_HEART:
      TITLE: "Le cœur brûlant"
      LORE: "Votre cœur s'embrase, générant des vagues de chaleurs dans un rayon de {_RADIUS} toutes les 1 secs pendant {_EFFECT_DURATION}, infligeant {_ATTACK}. Les ennemis sont ensuite brûlés, subissant {_EFFECT_ATTACK} toutes les {_EFFECT_FREQUENCY} pendant {_EFFECT_DURATION}"
    MOUNTAIN:
      TITLE: "L'écrasement"
      LORE: "L'écrasement inflige {_ATTACK} à tous les ennemis dans un rayon de {_RADIUS}. Les ennemis touchés sont enfoncés dans le sol pendant {_EFFECT_DURATION}"
  LEGGING:
    BURNING_HEART:
      TITLE: "Flamme renouvelée"
      LORE: "Pendant {_EFFECT_DURATION}, les dégâts qui devaient vous infliger la mort sont annulés. Si vous deviez-mourrir, vous vous immobilisez pendant une courte durée, avant de vous enflammer, infligeant {_ATTACK} dans un rayon de {_RADIUS}, brûlant les ennemis qui subissent {_EFFECT_ATTACK} pendant {_EFFECT_DURATION} toutes les {_EFFECT_FREQUENCY}."
  STAFF:
    BURNING_HEART:
      LORE: "Projette une boule de feu qui inflige {_ATTACK} tous les {_EFFECT_FREQUENCY} pendant {_EFFECT_DURATION} dans un rayon de {_RADIUS}. \nPeut aussi {_ATTACK-2}"
  CROSSBOW:
    BURNING_HEART:
      LORE: "Le carreau inflige {_ATTACK} avant de provoquer une déflagration dans un rayon de {_RADIUS}. Les ennemis touchés sont brûlés, subissant {_EFFECT_ATTACK} toutes les {_EFFECT_FREQUENCY} pendant {_EFFECT_DURATION}"
  BOW:
    BURNING_HEART:
      LORE: "La flèche inflige {_ATTACK} et brûle la cible, infligeant {_EFFECT_ATTACK} tous les {_EFFECT_FREQUENCY} pendant {_EFFECT_DURATION}. Si la cible est déjà brûlée, les ennemis dans un rayon de {_RADIUS} le sont aussi. Si la cible est touchée de nouveau, elle subit le double de dégâts."
GIFT:
  MEMORY:
    TITLE: "Mémoire"
    DAMAGE_1:
      TITLE: "Mémoire offensive"
      LORE: "Octroie {_ATTACK} et {_POWER}"
  WILL:
    TITLE: "Volonté"
    BURNING_HEART:
      TITLE: "Volonté du coeur brûlant"
    MOUNTAIN:
      TITLE: "Volonté de la montagne"
  INTELLECT:
    TITLE: "Intelligence"
    RANGE_1:
      TITLE: "Intelligence conceptuelle"
      LORE: "Octroie {_RANGE} de portée supplémentaire sur le don de volonté associé"
    RADIUS_1:
      TITLE: "Impact amélioré"
      LORE: "Octroie {_RADIUS} de zone d'effet supplémentaire sur le don de volonté associé"
ATTRIBUTE:
  RADIUS: "AOE"
  EFFECT: "Effet"
  PROJECTILE: "Projectile"
GUI:
  GIFT:
    ALTAR:
      INITIAL:
        TITLE: "Equipement / Arme"
      CHOOSE_CATEGORY:
        TITLE: "Fructifier les dons"
      CONSECRATE:
        TITLE: "Don : {_category}"
UTILITY:
  MAIN:
    CD:
      TITLE: "Cooldown"
    NOMANA:
      TITLE: "Pas assez de mana"
  GUI:
    UNAVAILABLE:
      TITLE: "Slot non disponible"
  GIFT:
    MEMORY:
      TITLE: "Don de mémoire"
    INTELLECT:
      TITLE: "Don d'intelligence"
    WILL:
      TITLE: "Don de volonté"
    UNAVAILABLE:
      TITLE: "Slot non disponible"
    MAXIMUM_REACHED:
      TITLE: "Slot non disponible"
      LORE: "Impossible d'ajouter un don supplémentaire"
    WILL_REQUIRED:
      TITLE: "Slot non disponible"
      LORE: "Intelligence sans volonté ne rime à rien"
    NO_GIFT:
      TITLE: "Slot non disponible"
      LORE: "Vous n'avez pas de don {_CATEGORY} dans votre inventaire"