ADMIN:
  COMMANDS:
    SUCCESS: "Commande exécutée avec succès !"
MESSAGE:
  PLAYER:
    MANA:
      NOT_ENOUGH: "Pas assez de mana"
    CD:
      SKILL:
        IN_PROGRESS: "Ce sort est en cooldown"
WAVE:
  TITLE: "Vague"
WEAPON:
  STAFF:
    TEST:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE} infligeant {_POWER}."
    LIMB_OF_WISDOM:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE}, rayon {_RADIUS} et infligeant {_POWER}"
SKILL:
  GENERAL:
    TEST:
      TITLE: "Le souffle du dragon"
      LORE: "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant {_POWER} dans un rayon de {_RADIUS}"
    DRAGON_BREATH:
      TITLE: "Le souffle du dragon"
      LORE: "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant {_POWER} dans un rayon de {_RADIUS}"
MEMORY:
  GENERAL:
    DAMAGE_1:
      TITLE: "Rune offensive"
      LORE: "Octroie {_ATTACK} et {_POWER}"
WILL:
  GENERAL:
    DRAGON_BREATH:
      TITLE: "Rune de volonté"
      LORE: "Octroie le souffle du dragon"
ATTRIBUTE:
  RADIUS: "AOE"
  RANGE: "Portée"
  PROJECTILE: "Projectile"
UTILITY:
  MAIN:
    CD:
      TITLE: "Cooldown"
    NOMANA:
      TITLE: "Pas assez de mana"