ADMIN:
  COMMANDS:
    SUCCESS: "Commande exécutée avec succès !"
WAVE:
  TITLE: "Vague"
WEAPON:
  STAFF:
    TEST:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE} infligeant {_POWER}."
    LIMB_OF_WISDOM:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE}, rayon {_RADIUS} et infligeant {_POWER}."
