ADMIN:
  COMMANDS:
    SUCCESS: "Commande exécutée avec succès !"
MESSAGE:
  PLAYER:
    MANA:
      NOT_ENOUGH: "Pas assez de mana"
    CD:
      SKILL:
        IN_PROGRESS: "Ce sort est en cooldown"
WAVE:
  TITLE: "Vague"
WEAPON:
  STAFF:
    TEST:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE} infligeant {_POWER}."
    LIMB_OF_WISDOM:
      TITLE: "L'Abattis de Sagesse"
      LORE: "Projette une boule de portée {_RANGE} et infligeant {_POWER}"
SKILL:
  HELMET:
    TEST:
      TITLE: "Le souffle du dragon"
      LORE: "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant {_POWER} dans un rayon de {_RADIUS}"
    DRAGON_BREATH:
      TITLE: "Le souffle du dragon"
      LORE: "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant {_POWER} dans un rayon de {_RADIUS}"
  STAFF:
    DRAGON_BREATH:
      LORE: "Projette une boule d'énergie destructrice, de portée {_RANGE}, rayon {_RADIUS} et infligeant {_POWER}"
GIFT:
  MEMORY:
    TITLE: "Mémoire"
    DAMAGE_1:
      TITLE: "Mémoire offensive"
      LORE: "Octroie {_ATTACK} et {_POWER}"
  WILL:
    TITLE: "Volonté"
    DRAGON_BREATH:
      TITLE: "Volonté : Souffle du dragon"
      LORE: "Octroie le souffle du dragon"
  INTELLECT:
    TITLE: "Intelligence"
    RANGE_1:
      TITLE: "Intelligence conceptuelle"
      LORE: "Octroie {_RANGE} de portée supplémentaire sur l'équipement appliqué"
ATTRIBUTE:
  RADIUS: "AOE"
  RANGE: "Portée"
  PROJECTILE: "Projectile"
GUI:
  GIFT:
    ALTAR:
      INITIAL:
        TITLE: "Equipement / Arme"
      CHOOSE_CATEGORY:
        TITLE: "Fructifier les dons"
      CONSECRATE:
        TITLE: "Don : {_category}"
UTILITY:
  MAIN:
    CD:
      TITLE: "Cooldown"
    NOMANA:
      TITLE: "Pas assez de mana"
  GUI:
    UNAVAILABLE:
      TITLE: "Slot non disponible"
  GIFT:
    MEMORY:
      TITLE: "Don de mémoire"
    INTELLECT:
      TITLE: "Don d'intelligence"
    WILL:
      TITLE: "Don de volonté"
    UNAVAILABLE:
      TITLE: "Slot non disponible"