command /testplanet:
    trigger:
        set {_loc} to location 1 meter above event-location
        set {_p} to event-player
        drawPlanet particle1 "soul flame", RGB 0, 0, 0, particle2 "flame", RGB2 0, 0, 0, center {_loc}, id "%{_p}%", radius 0.25, density 150, precision 100, bumpHeight 0.25, visibleRange 30, tps 1, second 2
        wait 5 seconds
        stopEffect "%{_p}%"

command /testitem:
    trigger:
        set {_p} to event-player
        if inventory of {_p} contains diamond:
            broadcast slot 0 of {_p}

command /benchmark:
    trigger:
        set {_p} to event-player
        set {_weapon} to item_create({_p}, "WEAPON", "STAFF", "LIMB_OF_WISDOM")
        set {_now} to now
        loop 100000 times:
            set {_toto} to item_nbt_get_tag({_weapon}, "TYPE")
        set {_after} to now

        broadcast "%difference between {_now} and {_after}%"

command /pig:
    trigger:
        set {_p} to event-player
        summon pig at location of {_p}
        set {_pig} to last spawned entity
        entity_nbt_set_tag({_pig}, "TYPE", "MOB")
        set maximum health of {_pig} to 1000
        set health of {_pig} to 1000

command /zombie:
    trigger:
        set {_p} to event-player
        mob_summon("ZOMBIE", 1, "A", location of {_p})
        set {_zombie} to last spawned entity
        set max health of {_zombie} to 900
        set health of {_zombie} to 900
        apply potion of slowness of tier 100 to {_zombie} for 999 days
        entity_nbt_set_tag({_zombie}, "TYPE", "MOB")
        entity_nbt_set_stat({_zombie}, "ATTACK", 10)

command /lisa:
    trigger:
        lisa_summon(random uuid)

command /tag:
    trigger:
        set the player's display name to "<red>[admin] <gold>%name of player%"
        set the player's tab list name to "<green>%player's name%"
        set all players' tab list footer to "Welcome%nl% to the Server!"

command /dragonbreath:
    trigger:
        set {_loc} to location 1 meter in front of player
        drawDragonBreath particle "endrod", speed 0.1, RGB 0, 0, 0, center {_loc}, id "tsunami", arcPitch 0.02, arcCount 50, arcDensity 200, arcSteps 5, arcLength 26, visibleRange 80

command /testspiral:
    trigger:
        set {_circle::*} to circle with radius 3 and density 2
        add {_circle::*} to {_circle::*}
        set {_bigcircle::*} to {_circle::*} scaled by 2
        loop size of {_circle::*} / 2 times:
            add vector line from {_circle::%loop-number%} to {_bigcircle::%loop-number + 7%} with density 5 to {_lines::*}
        # broadcast "%{_lines::*}%"
        show happy villager at location 8 in front of player offset by {_lines::*}

command /line-circle:
    trigger:
        set {_circle::*} to circle with radius 5 and density 1
        set {_bigcircle::*} to {_circle::*} scaled by 1.5
        loop size of {_circle::*} times:
            add vector line from {_circle::%loop-number%} to {_bigcircle::%loop-number%} with density 5 to {_lines::*}
        
        loop {_circle::*}:
            set {_loc} to location 10 in front of player offset by loop-value
            drawDot count 1, particle "flame", RGB 0, 0, 0, center {_loc}, rainbowMode true, visibleRange 32, pulseDelay 0, keepFor 10 ticks
            loop {_lines::*}:
                set {_loc1} to location 10 in front of player offset by loop-value-2
                drawDot count 1, particle "flame", RGB 0, 0, 0, center {_loc1}, rainbowMode true, visibleRange 32, pulseDelay 0, keepFor 10 ticks

command /line-vortex-2:
    trigger:
        set {_yaw} to yaw of player
        set {_pitch} to pitch of player + 90
        set {_frame} to frame with yaw {_yaw} and pitch {_pitch}
        set {_circle::*} to circle with radius 1.8 and density 1 in {_frame}
        add {_circle::*} to {_circle::*}
        
        set {_bigcircle::*} to {_circle::*} scaled by 2
        set {_smallcircle::*} to {_circle::*} scaled by 0.5
        loop size of {_circle::*} / 2 times:
            add vector line from {_circle::%loop-number%} to {_bigcircle::%loop-number + 7%} with density 5 to {_lines::*}
            add vector line from {_circle::%loop-number%} to {_smallcircle::%loop-number + 7%} with density 5 to {_lines::*}
        
        loop 20 times:
            loop {_lines::*}:
                set {_loc1} to location 10 in front of player offset by loop-value-2
                draw 5 of dust using dustOption(rgb(0,0,0), 0.5) at {_loc1}
            wait 1 tick
                # drawDot count 1, particle "critmagic", RGB 0, 0, 0, center {_loc1}, rainbowMode true, visibleRange 32, pulseDelay 0, keepFor 100 ticks

command /shield:
    trigger:
        # set {_item} to shield
        # set {_it} to item_nbt_set_tag_native({_it}, "{Damage:336}")
        set {_it} to 30
        # set {_item} to slot 40 of inventory of player
        # item_nbt_set_tag_native({_item}, "{Damage:0}")
        set {_item} to slot 40 of inventory of player
        loop 10 times:
            if player is holding a shield:
                broadcast "OHLDING"
            set {_item} to item_nbt_set_tag_native({_item}, "{Damage:%{_it}%}")
            set slot 40 of inventory of player to {_item}
            add 30 to {_it}
            wait 20 ticks

        # set slot 40 of inventory of player to {_it}

command /creeper:
    trigger:
        mob_summon("CREEPER", 1, "A", location of player)

command /mythicVoidArcher:
    trigger:
        mob_summon("VOID_ARCHER", 5, "A", location of player)
command /mythicVoidWarrior:
    trigger:
        mob_summon("VOID_WARRIOR", 1, "A", location of player)
command /mythicVoidWarriorCaptain:
    trigger:
        mob_summon("VOID_WARRIOR-CAPTAIN", 5, "A", location of player)
command /mythicVoidWarriorFly:
    trigger:
        mob_summon("VOID_WARRIOR-FLY", 5, "A", location of player)
command /mythicLavaWarrior:
    trigger:
        mob_summon("LAVA_WARRIOR", 5, "A", location of player)
command /mythicSpartan:
    trigger:
        mob_summon("NORMAL_SPARTAN", 5, "A", location of player)
command /mythicGouliath:
    trigger:
        mob_summon("BOSS_GOULIATH", 5, "A", location of player)
    
command /testrings:
    trigger:
        set {_p} to player
        set {_yaw} to yaw of {_p}
        set {_pitch} to pitch of {_p}
        set {_frame} to frame with yaw 90 and pitch 0
        set {_frame2} to frame with yaw 0 and pitch 0
        set {_circle::*} to circle with radius 5 and density 5 in {_frame}
        set {_circle2::*} to circle with radius 5 and density 5 in {_frame2}
        set {_loc} to location 1 meter above {_p}
        loop 100 times:
            loop {_circle::*}:
                draw 1 flame at location 1 meter above {_p} offset by loop-value-2 with extra 0
            loop {_circle2::*}:
                draw 1 flame at location 1 meter above {_p} offset by loop-value-2 with extra 0
            wait 1 tick


command /iaskriptgetitem <text> [<number=1>]:
    trigger:
        set {_item} to customitem "coeur_vaillant"
        give 1 of {_item} to player

command /burn_block <text>:
    trigger:
        set block at player to fire

command /cylinder:
    trigger:
        drawCylinder particle "flame", speed 0.02, center location of player, id "test", randomRotation false, isSolid false, radius 0.5, density 50, height 2, sideRatio 0, visibleRange 30
        wait 5 seconds
        stopEffect "test"
        
command /loopzombie:
    trigger:
        loop 50 times:
            summon zombie