function entity_get_tag(entity: entity, key: text) :: text:
  set {_res} to string tag "custom;%{_key}%" of nbt compound of {_entity}
  return {_res}

function entity_set_tag(entity: entity, key: text, value: text):
  set {_nbt} to nbt compound of {_entity}
  set tag "custom;%{_key}%" of {_nbt} to {_value}

function entity_set_tag_native(entity: entity, value: text):
  add nbt compound of {_value} to nbt compound of {_entity}