function parser_tier(tier: number) :: text:
  if {_tier} is 1:
    return "I"
  else if {_tier} is 2:
    return "II"
  else if {_tier} is 3:
    return "III"
  else if {_tier} is 4:
    return "IV"
  else if {_tier} is 5:
    return "V"
  else if {_tier} is 6:
    return "VI"
  else if {_tier} is 7:
    return "VII"
  else:
    return ""

function color_stat(stat: text, value: number) :: text:
  set {_statTxt} to {_value}
  if "COOLDOWN" contains {_stat}:
    return "%{_value}/20% sec"
  if "DEFENCE_REDUCTION" and "DEFENCE_REDUCTION_FACING" contains {_stat}:
    set {_statTxt} to "%{_value}%%{STAT::%{_stat}%::ICON_END}%"
  else if "DURABILITY" and "DURABILITY_MAX" contains {_stat}:
    return "%{_value}%"
  
  if {_value} > 0:
    return "§2+%{_statTxt}%"
  else:
    return "§c-%{_statTxt}%"