STAFF:
  DRAGON_BREATH:
    STATS:
      POWER: 10
      POWER_MULTIPLIER: 0.5
      COOLDOWN: 30
      RANGE: 5
      RADIUS: 1.5
      PROJECTILE_SPEED: 10
      PROJECTILE_AMOUNT: 1
  BURNING_HEART:
    ATTRIBUTES:
      - PROJECTILE
      - EFFECT
      - RADIUS
    STATS:
      POWER: 3
      POWER_MULTIPLIER: 0.5
      COOLDOWN: 30
      RANGE: 5
      RADIUS: 1.5
      PROJECTILE_SPEED: 10
      PROJECTILE_AMOUNT: 1
      EFFECT_DURATION: 60
      EFFECT_FREQUENCY: 20
HELMET:
  TEST:
    ITEM: dragon's breath
    STATS:
      POWER: 20
      POWER_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
      MANA: 70
  BURNING_HEART:
    ITEM: lava bucket
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      POWER: 3
      POWER_MULTIPLIER: 0.5
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 1.5
      MANA: 100
      EFFECT_DURATION: 100
      EFFECT_FREQUENCY: 20
CHESTPLATE:
  MOUNTAIN:
    ITEM: Oak Sapling
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 12
      ATTACK_MULTIPLIER: 0.5
      COOLDOWN: 20
      RADIUS: 5
      MANA: 100
      EFFECT_DURATION: 60