MAGE:
  TEST:
    ITEM: dragon's breath
    STATS:
      POWER: 20
      POWER_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
      MANA: 70
  DRAGON_BREATH:
    ITEM: allium
    STATS:
      POWER: 10
      POWER_MULTIPLIER: 0.7
      COOLDOWN: 300
      RANGE: 12
      RADIUS: 2
      MANA: 100