STAFF:
  DRAGON_BREATH:
    STATS:
      POWER: 10
      POWER_MULTIPLIER: 0.5
      COOLDOWN: 30
      RANGE: 5
      RADIUS: 1.5
      PROJECTILE_SPEED: 10
      PROJECTILE_AMOUNT: 1
  BURNING_HEART:
    ATTRIBUTES:
      - PROJECTILE
      - EFFECT
      - RADIUS
    STATS:
      ATTACK: 3
      ATTACK_MULTIPLIER: 0.5
      ATTACK-2: 10
      ATTACK-2_MULTIPLIER: 0.9
      COOLDOWN: 30
      RANGE: 5
      RADIUS: 1.5
      PROJECTILE_SPEED: 10
      PROJECTILE_AMOUNT: 1
      EFFECT_DURATION: 60
      EFFECT_FREQUENCY: 20
CROSSBOW:
  BURNING_HEART:
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 15
      ATTACK_MULTIPLIER: 0.8
      RADIUS: 1.5
      EFFECT_ATTACK: 3
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 60
      EFFECT_FREQUENCY: 20
BOW:
  BURNING_HEART:
    ATTRIBUTES:
      - PROJECTILE
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 15
      ATTACK_MULTIPLIER: 0.6
      RADIUS: 2
      EFFECT_ATTACK: 2
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 80
      EFFECT_FREQUENCY: 20
HELMET:
  TEST:
    ITEM: dragon's breath
    STATS:
      ATTACK: 20
      ATTACK_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
  BURNING_HEART:
    TRIGGER: "MANUAL"
    ITEM: redstone torch
    ATTRIBUTES:
      - EFFECT
    STATS:
      ATTACK: 20
      ATTACK_MULTIPLIER: 0.6
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_ATTACK: 5
      EFFECT_DURATION: 100
      EFFECT_FREQUENCY: 20
      RANGE: 8
      COOLDOWN: 140
CHESTPLATE:
  BURNING_HEART:
    ITEM: lava bucket
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 2
      ATTACK_MULTIPLIER: 0.1
      COOLDOWN: 600
      RADIUS: 6
      EFFECT_ATTACK: 5
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_DURATION: 160
      EFFECT_FREQUENCY: 20
  MOUNTAIN:
    ITEM: Oak Sapling
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 12
      ATTACK_MULTIPLIER: 0.5
      COOLDOWN: 20
      RADIUS: 5
      MANA: 100
      EFFECT_DURATION: 60
LEGGING:
  BURNING_HEART:
    ITEM: nether wart
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 10
      ATTACK_MULTIPLIER: 0.5
      COOLDOWN: 500
      RADIUS: 6
      EFFECT_ATTACK: 3
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_DURATION: 80
      EFFECT_FREQUENCY: 20