STAFF:
  BURNING_HEART:
    ATTRIBUTES:
      - PROJECTILE
      - EFFECT
      - RADIUS
    STATS:
      EFFECT_ATTACK: 10
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 60
      EFFECT_FREQUENCY: 20
      COOLDOWN: 30
      RANGE: 8
      RADIUS: 3
      ATTACK-2: 5
      ATTACK-2_MULTIPLIER: 0.5
      EFFECT_ATTACK-2: 5
      EFFECT_ATTACK_MULTIPLIER-2: 0.6
      EFFECT_DURATION-2: 80
      EFFECT_FREQUENCY-2: 20
      RADIUS-2: 2
      COOLDOWN-SPECIAL: 480
      PROJECTILE_AMOUNT: 1
  LIGHTNING:
    STATS:
      ATTACK: 3
      ATTACK_MULTIPLIER: 0.5
      COOLDOWN: 30
      COOLDOWN-SPECIAL: 5

CROSSBOW:
  BURNING_HEART:
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 15
      ATTACK_MULTIPLIER: 0.8
      RADIUS: 1.5
      EFFECT_ATTACK: 3
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 60
      EFFECT_FREQUENCY: 20
      KNOCKBACK: 3
BOW:
  BURNING_HEART:
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 5
      ATTACK_MULTIPLIER: 0.6
      COOLDOWN: 25
      RADIUS: 2
      EFFECT_ATTACK: 2
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 80
      EFFECT_FREQUENCY: 20
      KNOCKBACK: 1
SWORD:
  BURNING_HEART:
    STATS:
      ATTACK: 8
      ATTACK_MULTIPLIER: 0.6
      RADIUS: 3
      EFFECT_ATTACK: 4
      EFFECT_ATTACK_MULTIPLIER: 0.5
      EFFECT_DURATION: 80
      EFFECT_FREQUENCY: 20
      KNOCKBACK: 2
      DEFENCE_REDUCTION_FACING: 80
HELMET:
  TEST:
    ITEM: dragon's breath
    CUSTOM_ITEM: tete_brulee
    STATS:
      ATTACK: 20
      ATTACK_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
  BURNING_HEART:
    TRIGGER: MANUAL
    ITEM: redstone torch
    ATTRIBUTES:
      - EFFECT
    STATS:
      ATTACK: 20
      ATTACK_MULTIPLIER: 0.6
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_ATTACK: 5
      EFFECT_DURATION: 100
      EFFECT_FREQUENCY: 20
      COOLDOWN: 160
      KNOCKBACK: 5
      PROPULSION: 3
      USAGE_ADDITIONAL: 1
CHESTPLATE:
  BURNING_HEART:
    ITEM: lava bucket
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 2
      ATTACK_MULTIPLIER: 0.1
      COOLDOWN: 320
      RADIUS: 6
      EFFECT_ATTACK: 5
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_DURATION: 160
      EFFECT_FREQUENCY: 20
  MOUNTAIN:
    ITEM: Oak Sapling
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      ATTACK: 12
      ATTACK_MULTIPLIER: 0.5
      COOLDOWN: 20
      RADIUS: 5
      MANA: 100
      EFFECT_DURATION: 60
LEGGING:
  BURNING_HEART:
    ITEM: nether wart
    ATTRIBUTES:
      - RADIUS
      - EFFECT
    STATS:
      CHARITY: 2
      COOLDOWN: 500
      EFFECT_DURATION: 120
      EFFECT_FREQUENCY: 20
BOOT:
  BURNING_HEART:
    ITEM: stone
    ATTRIBUTES:
      - EFFECT
    STATS:
      ATTACK: 20
      ATTACK_MULTIPLIER: 0.6
      EFFECT_ATTACK_MULTIPLIER: 0.2
      EFFECT_ATTACK: 5
      EFFECT_DURATION: 100
      EFFECT_FREQUENCY: 20
      COOLDOWN: 160
      KNOCKBACK: 5
      PROPULSION: 3
      USAGE_ADDITIONAL: 1