MAGE:
  TEST:
    ITEM: dragon's breath
    STATS:
      POWER: 20
      POWER_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
      MANA: 70
  DRAGON_BREATH:
    ITEM: dragon's breath
    STATS:
      POWER: 20
      POWER_MULTIPLIER: 1
      COOLDOWN: 300
      RANGE: 8
      RADIUS: 5
      MANA: 100