STAFF:
  TEST:
    ITEM: carrot on a stick
    STATS:
      ATTACK: 10
      ATTACK_MULTIPLIER: 0.2
      COOLDOWN: 30
      RANGE: 5
      RADIUS: 1.5
  LIMB_OF_WISDOM:
    ITEM: carrot on a stick
    CUSTOM_ITEM: basic_staff
    WILL:
      BURNING_HEART:
        ITEM: carrot on a stick
        CUSTOM_ITEM: volonte_staff
    GIFTS:
      WILL_MAX: 1
      INTELLECT_MAX: 1
      MEMORY_MAX: 0
    STATS:
      ATTACK: 5
      ATTACK_MULTIPLIER: 0.2
      COOLDOWN: 30
      RANGE: 8
      PROJECTILE_SPEED: 10
      PROJECTILE_AMOUNT: 1
CROSSBOW:
  ARMADILLO:
    ITEM: crossbow
    WILL:
      BURNING_HEART:
        ITEM: crossbow
    GIFTS:
      WILL_MAX: 1
      INTELLECT_MAX: 1
      MEMORY_MAX: 0
    STATS:
      ATTACK: 12
      ATTACK_MULTIPLIER: 0.5
      ATTACK_SPEED: 1
      PROJECTILE_AMOUNT: 1
      KNOCKBACK: 3
BOW:
  ARROWSPIKE:
    ITEM: bow
    WILL:
      BURNING_HEART:
        ITEM: bow
    GIFTS:
      WILL_MAX: 1
      INTELLECT_MAX: 1
      MEMORY_MAX: 0
    STATS:
      ATTACK: 8
      ATTACK_MULTIPLIER: 0.5
      KNOCKBACK: 1
SWORD:
  DARD:
    ITEM: iron sword
    WILL:
      BURNING_HEART:
        ITEM: iron sword
        CUSTOM_ITEM: volonte_sword
    GIFTS:
      WILL_MAX: 1
      INTELLECT_MAX: 1
      MEMORY_MAX: 0
    STATS:
      ATTACK: 8
      ATTACK_MULTIPLIER: 0.5
      KNOCKBACK: 2
      DEFENCE_FACING: 70