TAG:
  DAMAGE_CATEGORY: "EXPLOSION"
STAT:
  HEALTH: 5
  HEALTH_MULTIPLIER: 1
  ATTACK: 3
  ATTACK_MULTIPLIER: 4
  DEFENCE: 0
  SPEED: 1
  SPEED_MULTIPLIER: 0.5
EQUIPMENT:
  HELMET: leather helmet
  2:
    HELMET: iron helmet
  3:
    HELMET: iron helmet
    CHESTPLATE: iron chestplate