BOSS:
  - BOSS_GOULIATH
NORMAL:
  - ZOMBIE
  - SKELETON
  - CREEPER
  - SPIDER
VOID:
  - VOID_ARCHER
  - VOID_WARRIOR
  - VOID_WARRIOR_CAPTAIN
POISON:
  - POISON_SPIDER
LAVA:
  - LAVA_WARRIOR
NECROMANCER:
  - NECROMANCER_SKELETON_NECROMANCER
NECROMANCER_CREATURE:
  - NECROMANCER_SKELETON_CREATURE_DEAD-BABY