CASTLE:
  THRONE: "x: 111, y: 40, z: 61, yaw: 90, pitch: -3"
  ARTIFACT: "x: -76, y: 24, z: 24"
  FOUNTAIN: "x: -36, y: 9, z: -13"
  GATE_A: "x: 69, y: 4, z: -97"
  GATE_B: "x: 50, y: 9, z: 51"
  GATE_C: "x: -61, y: 9, z: -137"
  GATE_D: "x: -119, y: 9, z: -13"