function test_i18n_items(p: player):
  send "§5Testing i18n items" to the console
  set {_originLang} to player_store_setting_get({_p}, "lang")
  player_store_setting_set({_p}, "lang", "fr-FR")
  
  it "Test get item title":
    set {_item} to diamond sword
    set {_item} to item_nbt_set_tag({_item}, "TYPE", "WEAPON")
    set {_item} to item_nbt_set_tag({_item}, "CATEGORY", "STAFF")
    set {_item} to item_nbt_set_tag({_item}, "ID", "TEST")

    set {_titleFr} to i18n_item_attr({_p}, {_item}, "TITLE")
    set {_referenceFr} to yaml value "WEAPON.STAFF.TEST.TITLE" from "YAML-LANG-fr-FR"
    assert if {_titleFr} is {_referenceFr} with message "name should be %{_referenceFr}%. Got %{_titleFr}%"

  it "Test get item lore":
    set {_item} to diamond sword
    set {_item} to item_nbt_set_tag({_item}, "TYPE", "WEAPON")
    set {_item} to item_nbt_set_tag({_item}, "CATEGORY", "STAFF")
    set {_item} to item_nbt_set_tag({_item}, "ID", "TEST")
    set {_loreFr} to i18n_item_attr({_p}, {_item}, "LORE")
    set {_referenceFr} to yaml value "WEAPON.STAFF.TEST.LORE" from "YAML-LANG-fr-FR"
    assert if {_loreFr} is {_referenceFr} with message "name should be %{_referenceFr}%. Got %{_titleFr}%"

  it "Test i18n_item_lore":
    set {_it} to item_create({_p}, "SKILL", "HELMET", "TEST")
    set {_attackStat} to {SKILL::HELMET::TEST::ATTACK}
    set {_attackMultiplierStat} to {SKILL::HELMET::TEST::ATTACK_MULTIPLIER}
    set {_radiusStat} to {SKILL::HELMET::TEST::RADIUS}

    player_store_stat_set({_p}, "ATTACK", 0)
    set {_radiusRefIcon} to {STAT::RADIUS::ICON}
    set {_radiusRefColor} to {STAT::RADIUS::COLOR}
    set {_attackRefIcon} to {STAT::ATTACK::ICON}
    set {_attackRefColor} to {STAT::ATTACK::COLOR}
    set {_attackStat} to (player_store_stat_get({_p}, "ATTACK") * {_attackMultiplierStat}) + {_attackStat}

    set {_loreAfter} to "Le souffle du dragon repousse les ennemis avant d'infliger des dégâts en bout de course, infligeant %{_attackRefColor}%%{_attackRefIcon}%%{_attackStat}%§f dans un rayon de %{_radiusRefColor}%%{_radiusRefIcon}%%{_radiusStat}%§f"
    set {_lore} to i18n_item_lore({_p}, {_it})
    assert if {_loreAfter} is {_lore} with message "lore should be %{_loreAfter}% §aGot %{_lore}%"

  it "Test i18n_item_lore_to_list":
    set {_lore} to "Je suis Cédric Baillet, développeur de Fort Lisa. J'espère de tout coeur que le jeu vous plaira !"
    set {_res::*} to i18n_item_lore_to_list({_lore})
    set {_idxes::*} to all indexes of {_res::*}
    assert if amount of {_idxes::*} is ceil(length of {_lore}/{LORE_LENGTH_MAX}) with message "Got %amount of {_idxes::*}%"

  player_store_setting_set({_p}, "lang", "fr-FR")