on directory changes at "plugins/Skript/scripts/fort-lisa/src/entities/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/entities/npc/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/events/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/game/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/game/store/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/i18n/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/gifts/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/skills/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/skills/general/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/store/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/weapons/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/weapons/staffs/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/location/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/action/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/ai/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/bestiary/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/store/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/action/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/interfaces/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/interfaces/guis/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/interfaces/menus/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/stat/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/store/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/waves/":
   reload script file fileManager_getRelativePath(event-path)

