on directory changes at "plugins/Skript/scripts/fort-lisa/src/events/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/i18n/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/stores/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/stores/":
   reload script file fileManager_getRelativePath(event-path)

