on directory changes at "plugins/Skript/scripts/fort-lisa/src/entities/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/events/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/i18n/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/weapons/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/items/weapons/staffs/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/mobs/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/action/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/stat/":
   reload script file fileManager_getRelativePath(event-path)

on directory changes at "plugins/Skript/scripts/fort-lisa/src/players/store/":
   reload script file fileManager_getRelativePath(event-path)

