NOCOLLISION:
- carrot on a stick
- air
- rail
- flower pot
- carpets
- fire
- torch
- wall torch
- cobweb
- conduit
- end rod
- signs
- water
- lava
- dandelion
- poppy
- azure bluet
- blue orchid
- allium
- red tulip
- orange tulip
- white tulip
- pink tulip
- oxeye daisy
- lilac
- rose_bush
- peony
- cornflower
- lily of the valley
- wither rose
- sunflower
- short grass
- tall grass
- redstone wire
- lever
- redstone torch
- redstone wall torch
- tripwire hook
- tripwire
- repeater
- comparator
- daylight detector
- campfire
- soul campfire
- waterlogged east facing unlit signal campfire
- upper height grass