#Give a skill to the player
function gift_give(p: player, type: text, category: text, id: text) :: item:
  set {_tier} to {%{_type}%::%{_category}%::%{_id}%::TIER}
  set {_gift} to item_create({_p}, {_type}, {_category}, {_id})
  set {_gift} to item_nbt_set_stat({_gift}, "TIER", {_tier})
  set {_name} to name of {_gift}
  set {_tierTxt} to parser_tier({_tier})
  set name of {_gift} to "%{_name}% %{_tierTxt}%"
  player_store_gift_give({_p}, {_gift})
  return {_gift}