command /testplanet:
    trigger:
        set {_loc} to location 1 meter above event-location
        set {_p} to event-player
        drawPlanet particle1 "redstone", RGB 0, 255, 10, particle2 "redstone", RGB2 0, 10, 255, center {_loc}, id "%{_p}%", radius 0.25, density 150, precision 100, bumpHeight 0.25, visibleRange 30, tps 1, second 2
        wait 5 seconds
        stopEffect "%{_p}%"

command /testitem:
    trigger:
        set {_p} to event-player
        if inventory of {_p} contains diamond:
            broadcast slot 0 of {_p}

command /benchmark:
    trigger:
        set {_p} to event-player
        set {_weapon} to item_create({_p}, "WEAPON", "STAFF", "LIMB_OF_WISDOM")
        set {_now} to now
        loop 100000 times:
            set {_toto} to item_get_tag({_weapon}, "TYPE")
        set {_after} to now

        broadcast "%difference between {_now} and {_after}%"

command /pig:
    trigger:
        set {_p} to event-player
        summon pig at location of {_p}
        set {_pig} to last spawned entity
        entity_nbt_set_tag({_pig}, "TYPE", "MOB")
        set maximum health of {_pig} to 1000
        set health of {_pig} to 1000

command /zombie:
    trigger:
        set {_p} to event-player
        summon zombie at location of {_p}
        set {_zombie} to last spawned entity
        entity_nbt_set_tag({_zombie}, "TYPE", "MOB")
        entity_nbt_set_stat({_zombie}, "ATTACK", 10)

command /citizen:
    trigger:
        lisa_remove()
        lisa_summon()

command /wave:
    trigger:
        wave_start(1, world of player)