CASTLE:
  THRONE: "x: 130, y: -27, z: 2, yaw: 0, pitch: 0"
  ENTRANCES:
    - "x: 130, y: -30, z: 44"
    - "x: 174, y: -30, z: 2"
    - "x: 129, y: -30, z: -43"
    - "x: 84, y: -30, z: 2"
SPAWNS:
  MEDIUM:
    - "x: 250, y: -30, z: 2"
    - "x: 131, y: -30, z: -122"
    - "x: 3, y: -30, z: 2"