CASTLE:
  THRONE: "x: 111, y: 40, z: 60"
  ENTRANCES:
    - "x: 60, y: 36, z: 70"- "x: -8, y: 36, z: 70"
    - "x: 5, y: 44, z: -12"
    - "x: 67, y: 38, z: -36"
    - "x: 113, y: 32, z: 128"
    - "x: 85, y: 36, z: 26"
    - "x: 100, y: 37, z: 16"
    - "x: 81, y: 36, z: 87"
SPAWNS:
  MEDIUM:
    - "x: 91, y: 35, z: 116"
    - "x: 41, y: 38, z: 96"
    - "x: 43, y: 37, z: 36"
    - "x: 89, y: 35, z: -4"
    - "x: 50, y: 35, z: 16" 
  FAR:
    - "x: -8, y: 36, z: 70"
    - "x: 5, y: 44, z: -12"
    - "x: 67, y: 38, z: -36"
    - "x: 113, y: 32, z: 128"
