function test_item_main(p: player):
  test_item_item({_p})
  test_item_nbt({_p})
  test_item_weapon({_p})
  test_item_skill({_p})
  test_item_gift({_p})

function test_item_main_detail(p: player, type: text):
  if {_type} is "item":
    test_item_item({_p})
    test_item_nbt({_p})
  if {_type} is "weapon":
    test_item_weapon({_p})
  if {_type} is "skill":
    test_item_skill({_p})
  if {_type} is "gift":
    test_item_gift({_p})